--Lab 2 ? Week 3 (Multi-Line Functions)

--Q1

--GROUP BY <COMMA SEPERATED FIELDLIST>, HAVING <CONDITIONAL STATEMENTS, BOLLEAN EXPRESSION>
-- 7 AGGREGATE FUNCTIONS = SUM,COUNT,AVG,MIN,MAX,VAR,STDDEV
